import shared from "@storeforge/config/eslint.js";

// next-env.d.ts is auto-generated by Next.js itself (next dev/build rewrite
// it) -- Next's own eslint config always excludes it too.
export default [...shared, { ignores: ["next-env.d.ts"] }];
